### PR TITLE
be like sadhu

### PR DESCRIPTION
**Pull request by mmSohan**
valo hoye ja.

### CODE REVIEW

**Comment by mirsazzathossain** [comment]
ami vlai vhi.

**Comment by mmSohan** [comment]
pagol ki kakhno nijeke pagol bole?

**Comment by mirsazzathossain** [comment]
eha merge krar upojugi nohe balok notun kisu try maro.

**Comment by mmSohan** [comment]
tumi kichu try maro.then dekhi edit korte pari kina.

**Pull request merged**
